<a href="https://colab.research.google.com/github/MostDeadDeveloper/ArabicCompetitiveProgramming/blob/master/challenge-5b.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Before you turn this problem in, make sure everything runs as expected. First, **restart the kernel** (in the menubar, select Kernel$\rightarrow$Restart) and then **run all cells** (in the menubar, select Cell$\rightarrow$Run All).

Make sure you fill in any place that says `YOUR CODE HERE` or "YOUR ANSWER HERE", as well as your name and collaborators below:

In [ ]:
NAME = "Carl John Reyes Vinas"
COLLABORATORS = ""

---

# Challenge 5B: Solving $A\vec{x} = \lambda \vec{x}$

> _Linear relationships can be captured with a straight line on a graph. Linear relationships are easy to think about.... Linear systems have an important modular virtue: you can take them apart, and put them together again — the pieces add up._
>
> — James Gleick in _Chaos: Making a New Science_ (1987)

The first part of this challenge should have given you a feel for how people turn the cranks and make matrices do useful stuff in practice (and by 'useful' I mean solving equations—you use equations in your daily life, right?)

This part is about the theory.

So much of what makes modern-day machine learning work won't make sense if you don't have a systematic understanding of what it means for something to change _linearly_: that is, if you double the input, you double the output. No hidden suprises.

In some sense a linear transformation is the simplest nontrivial kind of response your system can have (as opposed to trivial ones like zero or constant responses), and it's no accident that we have collectively decided to make it the bedrock upon which we understand all other kinds of change.

The behaviour of linear transformations only becomes clearer when we consider what they _preserve_ in the course of morphing spaces, and so by studying them in this challenge you should:

* [ ] know what a vector space is, and what having such a structure implies about the stuff you can and cannot do
* [ ] get into the habit of seeing beyond individual vectors and looking for their 'completions'; what this means will hopefully become clearer later on
* [ ] be able to reformulate a thorny transformation into components that are easier to work with

In particular, the main star of the show is the matrix equation $A\vec{x} = \lambda \vec{x}$, and you may think of everything else that follows as mere stepping stones.

## Definition: (vector space)

A **vector space** or **linear space** $V$ is a set of vectors where the following properties are always satisfied:

1. [additive identity] The zero vector $\vec{0}$ is in $V$; or in other words there's a vector $\vec{0}$ in $V$ such that $\vec{0} + \vec{v} = \vec{v}$ is always true.
2. [additive inverse] Any vector $\vec{v}$ in $V$ has a corresponding inverse vector $\vec{-v}$ so that $\vec{v} + (\vec{-v}) = \vec{0}$.
3. [addition is commutative] $\vec{v} + \vec{w} = \vec{v} + \vec{w}$ for all $\vec{v}, \vec{w} \in V$.
4. [addition is associative] $\vec{v_1} + (\vec{v_2} + \vec{v_3}) = (\vec{v_1} + \vec{v}) + \vec{v}$ for all $\vec{v_1}, \vec{v_2}, \vec{v_3} \in V$.
5. [multiplicative identity] For all $\vec{v}$ in $V$, we have $1 \vec{v} = \vec{v}$.
6. [multiplication is associative] $a(b\vec{v}) = (ab)\vec{v}$ for all scalars $a, b$ and $\vec{v} \in V$.
7. [scalar addition is distributive] $(a + b)\vec{v} = a\vec{v} + b\vec{v}$ for all scalars $a, b$ and $\vec{v} \in V$.
8. [vector addition is distributive] $a(\vec{v} + \vec{w}) = a\vec{v} + a\vec{w}$ for all scalars $a$ and $\vec{v}, \vec{w} \in V$.

---

Don't fret: by this point every single one of these properties should already be familiar to you: we're just consolidating them into one list.

Also, this is what it really means for a _vector_ to be a _vector_. It's not about having magnitude or direction but about being an element of a _vector space_, obeying all the properties above and interacting with other vectors in precisely the ways we have listed.

This also means that there are 'vectors' that are not necessarily floating arrows in space, as the following example will show.


## Example: Light switches

Consider $n$ light switches, each of which can take either two states: ON or OFF. Form the set $V$ of possible _configurations_ these light switches can be in, so for example:

$$
\vec{v} = \begin{bmatrix} ON \\ ON \\ \dots \\ ON \end{bmatrix}
$$

is one such configuration.

Now, let's say 'adding' two configurations means, for each corresponding pair of switch entries, you leave it ON if there is _exactly_ one switch entry in the pair that's ON. Example:

$$
\begin{bmatrix}
ON \\
ON \\
OFF \\
OFF
\end{bmatrix}
+
\begin{bmatrix}
ON \\
OFF \\
ON \\
OFF
\end{bmatrix}
=
\begin{bmatrix}
OFF \\
ON \\
ON \\
OFF
\end{bmatrix}
$$

Furthermore, 'multiplying' a configuration by ON means _leaving ON_ only the switches that were already ON, and multiplying by OFF means turning OFF everything. So:

$$
(ON)
\begin{bmatrix}
OFF \\
ON \\
ON \\
OFF
\end{bmatrix}
=
\begin{bmatrix}
OFF \\
ON \\
ON \\
OFF
\end{bmatrix}
$$

and

$$
(OFF)
\begin{bmatrix}
OFF \\
ON \\
ON \\
OFF
\end{bmatrix}
=
\begin{bmatrix}
OFF \\
OFF \\
OFF \\
OFF
\end{bmatrix}
$$

Then $V$ is a vector space.

---

You might also remember the notion of a **vector subspace** from the first session. We can now restate its definition more compactly: it is a subset of a vector space $V$ which is also a vector space.

## Problem 1: Show that $V$ in the light switch example is a vector space.

Note that your only scalars are in the set $\{ON, OFF\}$.


### Answer:

A good way to answer this is proving that all possible values and combinations in this vector space applies to the needed properties of any vector space.

Luckily, we can represent all possible combinations of the two possible values in this vector space through these two vectors:
- $ \vec{v_1}  = \begin{bmatrix}
ON \\
ON \\
OFF \\
OFF
\end{bmatrix}
\vec{v_2}  =
\begin{bmatrix}
ON \\
OFF \\
ON \\
OFF
\end{bmatrix}
$

We can also represent the only two possible values of the vector space which is $a=ON$ and $b=OFF$.

Throughout the different properties, we will use $ \vec{v_1}$, $ \vec{v_2}$, $a$ and $b$ to prove that these properties work for all values and combinations of the vector space.

We consider V as a vector space since it follows all the given properties below:
1. **[additive identity]**: this property is fullfiled since there exists a vector $\vec{0}$ in $V$ such that $\vec{0} + \vec{v} = \vec{0}$ is always true. Specifically this is a vector where it only contains b.
- $\vec{0} = \begin{bmatrix} OFF \\ OFF \\ \dots \\ OFF \end{bmatrix} or \begin{bmatrix} OFF \\ \end{bmatrix} $

2. **[additive inverse]**: This property applies, since every $\vec{v}$ in $V$ has a corresponding inverse vector $\vec{-v}$ so that $\vec{v} + (\vec{-v}) = \vec{0}$. The corresponding inverse vector is itself. This can be further seen below on the given vectors:
- $ \vec{v_1} + \vec{v_1} =\vec{0} $
- $ \vec{v_2} + \vec{v_2} = \vec{0} $
3. **[addition is commutative]**: This property applies as well for all possible combinations and values in the vector space as we can see below:
- $ \vec{v_1} + \vec{v_2} = \begin{bmatrix}
OFF \\
ON \\
ON \\
OFF
\end{bmatrix}$
- $ \vec{v_2} + \vec{v_1} = \begin{bmatrix}
OFF \\
ON \\
ON \\
OFF
\end{bmatrix} $
4. **[addition is associative]**: this property also applies for this vector space, we can prove this by trying out if the property holds for two possible cases, which is:
- ($ \vec{v_1} + \vec{v_2}) + \vec{v_2} = $
- ($ \vec{v_1} + \vec{v_2}) + \vec{v_1}$

For the first Case:
- ($ \vec{v_1} + \vec{v_2}) + \vec{v_1} = \begin{bmatrix}
ON \\
OFF \\
ON \\
OFF
\end{bmatrix}
$
- $ \vec{v_1} + (\vec{v_2} + \vec{v_1}) = \begin{bmatrix}
ON \\
OFF \\
ON \\
OFF
\end{bmatrix}
$

And thus since they are both equal, the property holds for the first case.

For the Second Case:
- ($ \vec{v_1} + \vec{v_2}) + \vec{v_2} = \begin{bmatrix}
OFF \\
OFF \\
OFF \\
OFF
\end{bmatrix}
$

- $ \vec{v_1} + (\vec{v_2} + \vec{v_2}) = \begin{bmatrix}
OFF \\
OFF \\
OFF \\
OFF
\end{bmatrix}
$

Since for both case holds, the "addition is associative" holds for all values and combinations.

5. **[multiplicative identity]**: For all $\vec{v}$, we have $(ON)(\vec{v}) = \vec{v}$

6. **[multiplication is associative]** $a(b\vec{v}) = (ab)\vec{v}$ for all scalars $a, b$ and $\vec{v} \in V$.

Supposing $\vec{v}$ is any vector in this vector space,

If  $a = OFF$, the property still holds:
- $a(b\vec{v}) = (ab)\vec{v}$
- $OFF(b\vec{v}) = ((OFF)(b))\vec{v}$
- $OFF(b\vec{v}) = (OFF)\vec{v}$
- $OFF = OFF$
 - anything multiplied to OFF, results in the zero vector ot a vector with OFF.


If  $a = ON$ , the property still holds:
- $a(b\vec{v}) = (ab)\vec{v}$
- $ON(b\vec{v}) = ((ON)(b))\vec{v}$
- $(b\vec{v}) = (b)\vec{v}$
- $(b)\vec{v} = (b)\vec{v}$
 - due to the multiplicative identity.

Since all values are equal for all cases, this property works for this vector space.

7. **[scalar addition is distributive]** $(a + b)\vec{v} = a\vec{v} + b\vec{v}$ for all scalars $a, b$ and $\vec{v} \in V$.

If all $a$ $b$, $\vec{v}$ is OFF case:
- If this is the case, the property still holds:
- $(a + b)\vec{v} = a\vec{v} + b\vec{v}$
- $(a + b)\vec{v} = (OFF)\vec{v} + (OFF)\vec{v}$
- $(OFF + OFF)\vec{v} = (OFF)\vec{v} + (OFF)\vec{v}$
- $(OFF)\vec{v} = (OFF)\vec{v} + (OFF)\vec{v}$
 - due to the additive identity
- $(OFF)\vec{v} = (OFF)\vec{v} + (OFF)\vec{v}$
- $OFF = OFF + OFF$
- $OFF = OFF$

If a and b is ON case:
- $(a + b)\vec{v} = a\vec{v} + b\vec{v}$
- $(ON + ON)\vec{v} = ON(\vec{v}) + ON(\vec{v})$
- $(OFF)\vec{v} = ON(\vec{v}) + ON(\vec{v})$
- $(OFF)\vec{v} = \vec{v} + \vec{v}$
 - due to the multiplicative identity.
- $OFF = \vec{v} + \vec{v}$
- $OFF = OFF$
 - following the additive inverse property

For a=ON b=OFF or a=OFF, b=ON case:
- $(a + b)\vec{v} = a\vec{v} + b\vec{v}$
- $(ON + OFF)\vec{v} = ON\vec{v} + OFF\vec{v}$
- $(ON)\vec{v} = ON\vec{v} + OFF\vec{v}$
- $\vec{v} = \vec{v} + OFF $
- $\vec{v} = \vec{v}$
 - following the additive identity property.

8. **[vector addition is distributive]** $a(\vec{v_1} + \vec{v_2}) = a\vec{v_1} + a\vec{v_2}$ for all scalars $a$ and $\vec{v_1}, \vec{v_2} \in V$.

Applying this property, to both $\vec{v_1} + \vec{v_2}$:

Supposing $a$ is a value of OFF:
- $a(\vec{v_1} + \vec{v_2}) = a\vec{v_1} + a\vec{v_2}$
- $OFF(\vec{v_1} + \vec{v_2}) = a\vec{v_1} + a\vec{v_2}$
- $OFF(\vec{v_1} + \vec{v_2}) = OFF\vec{v_1} + OFF\vec{v_2}$
- $OFF(\begin{bmatrix}OFF \\ON \\ON \\OFF\end{bmatrix}) = (OFF)\vec{v_1} + (OFF)\vec{v_2}$
- $OFF(\begin{bmatrix}OFF \\ON \\ON \\OFF\end{bmatrix}) = (OFF) + (OFF)$
- $OFF(\begin{bmatrix}OFF \\ON \\ON \\OFF\end{bmatrix}) = (OFF) + (OFF)$
- $OFF = (OFF) + (OFF)$
- $OFF = OFF$

Supposing $a$ is a value of ON:
- $a(\vec{v_1} + \vec{v_2}) = a\vec{v_1} + a\vec{v_2}$
- $ON(\vec{v_1} + \vec{v_2}) = a\vec{v_1} + a\vec{v_2}$
- $ON(\vec{v_1} + \vec{v_2}) = ON\vec{v_1} + ON\vec{v_2}$
- $ON(\begin{bmatrix}OFF \\ON \\ON \\OFF\end{bmatrix}) = (ON)\vec{v_1} + (ON)\vec{v_2}$
- $ON(\begin{bmatrix}OFF \\ON \\ON \\OFF\end{bmatrix}) = \vec{v_1} + \vec{v_2}$
- $\begin{bmatrix}OFF \\ON \\ON \\OFF\end{bmatrix} = \vec{v_1} + \vec{v_2}$
- $\begin{bmatrix}OFF \\ON \\ON \\OFF\end{bmatrix} = \begin{bmatrix}OFF \\ON \\ON \\OFF\end{bmatrix}$



## Definition: (linear combination)

A **linear combination** of vectors $\vec{v_1}, \dots, \vec{v_n}$ in a vector space $V$ is simply a vector $\vec{v}$ in $V$ where:

$$
\vec{v} = \sum_{i=1}^n {a_i v_i}
$$

for scalars $a_i$. In other words, it is a _weighted sum_ of $\vec{v_1}, \dots, \vec{v_n}$.

## Definition: (span)

A set of vectors $\vec{v_1}, \dots, \vec{v_n}$ are said to **span** $V$ if and only if every vector in $V$ can be written as a linear combination of $\vec{v_1}, \dots, \vec{v_n}$.

Alternatively, the **span** of $\vec{v_1}, \dots, \vec{v_n}$ is the set $\text{Span } (\vec{v_1}, \dots, \vec{v_n})$ of all their linear combinations.

## Example: Standard basis vectors

The standard basis vectors $\vec{e_1} = \begin{bmatrix} 1 \\ 0 \end{bmatrix}$ and $\vec{e_2} = \begin{bmatrix} 0 \\ 1 \end{bmatrix}$ span $\mathbb{R}^2$. Why? Because you can write any vector $\vec{v}$ in $\mathbb{R}^2$ as:

$$
\vec{v} = \begin{bmatrix} v_1 \\ v_2 \end{bmatrix} = v_1 \begin{bmatrix} 1 \\ 0 \end{bmatrix} + v_2 \begin{bmatrix} 0 \\ 1 \end{bmatrix}
$$

## Definition: (linear independence)

A set of vectors $\vec{v_1}, \dots, \vec{v_n}$ are said to be **linearly independent** if none of $\vec{v_i}$ can be written as a linear combination of the others.

Equivalently, they are linearly independent if the only solution to

$$
a_1 \vec{v_1} + \dots + a_n \vec{v_n} = \vec{0}
$$

is for all the $a_i$ to be equal to zero.

## Example: Standard basis vectors are linearly independent

The standard basis vectors in $\mathbb{R}^3$: $\vec{e_1} = \begin{bmatrix} 1 \\ 0 \\ 0 \end{bmatrix}$, $\vec{e_2} = \begin{bmatrix} 0 \\ 1 \\ 0 \end{bmatrix}$, and $\vec{e_3} = \begin{bmatrix} 0 \\ 0 \\ 1 \end{bmatrix}$

are linearly independent. To see this, form:

$$
a_1 \begin{bmatrix} 1 \\ 0 \\ 0 \end{bmatrix}
+
a_2 \begin{bmatrix} 0 \\ 1 \\ 0 \end{bmatrix}
+
a_3 \begin{bmatrix} 0 \\ 0 \\ 1 \end{bmatrix}
=
\begin{bmatrix} 0 \\ 0 \\ 0 \end{bmatrix}
$$

from which it is clear that $a_1 = a_2 = a_3 = 0$.

---

To make our lives easier, we shall denote the set of vectors $\vec{v_1}, \dots, \vec{v_n}$ as $\{ \vec{v_i} \}_{i=1}^n$ or simply $\{\vec{v_i}\}$ if the number of elements is clear from context.

## Proposition I: Linear independence and span

Let $\{\vec{v_i}\}_{i=1}^k$ be vectors in $\mathbb{R}^n$. Form the $n \times k$ matrix $A = [\vec{v_1}, \dots, \vec{v_k}]$ whose ith column is simply $\vec{v_i}$. Then:

1. $\{\vec{v_i}\}$ are linearly independent if the row-reduced matrix $\tilde{A}$ has a pivotal 1 in every column.
2. $\{\vec{v_i}\}$ span $\mathbb{R}^n$ if and only if $\tilde{A}$ has a pivotal 1 in every row.

## Problem 2: Using Proposition I

a. Given $\vec{w_1} = \begin{bmatrix} 2 \\ 1 \\ 1 \end{bmatrix}$, $\vec{w_2} = \begin{bmatrix} 1 \\ -1 \\ 1 \end{bmatrix}$, $\vec{w_3} = \begin{bmatrix} 3 \\ 0 \\ 2 \end{bmatrix}$, and $\vec{v} = \begin{bmatrix} 3 \\ 3 \\ 1 \end{bmatrix}$

Is $\vec{v}$ in the span of $\{w_i\}$? Check this using row reduction.

b. Given $\vec{w_1} = \begin{bmatrix} 1 \\ 2 \\ 3 \end{bmatrix}$, $\vec{w_2} = \begin{bmatrix} -2 \\ 1 \\ 2 \end{bmatrix}$, $\vec{w_3} = \begin{bmatrix} -1 \\ 1 \\ -1 \end{bmatrix}$

Are they linearly independent? Do they span $\mathbb{R}^3$? Check these using row reduction.



In [ ]:
import numpy as np
# Problem 2a
# To check if vector v is in the span of w, we can use row reduction and find if there exists scalars for
# w_1, w_2, and w_3 where it would result in vector v.
# Listed below are the step by step row reduction for these vectors:
print('Answer to Problem 2.a')
print('Row Operations for First Initial Matrix')
initial_matrix_1 = np.matrix(
    [[2., 1., 3,3],
    [1., -1., 0,3],
    [1., 1., 2,1]]
)
print('Initial Matrix #1:')
display(initial_matrix_1)

operation = np.matrix(
    [[1/2, 0, 0.],
    [0, 1, 0.],
    [0, 0, 1.]]
)
initial_matrix_1 = operation * initial_matrix_1

print('Matrix #1 after Operation :')
display(initial_matrix_1)

operation = np.matrix(
    [[1, 0, 0.],
    [-1, 1, 0.],
    [0, 0, 1.]]
)
initial_matrix_1 = operation * initial_matrix_1

print('Matrix #1 after Operation :')
display(initial_matrix_1)

operation = np.matrix(
    [[1, 0, 0.],
    [0, 1, 0.],
    [-1, 0, 1.]]
)
initial_matrix_1 = operation * initial_matrix_1

print('Matrix #1 after Operation :')
display(initial_matrix_1)

# ===============
operation = np.matrix(
    [[1, 0, 0.],
    [0, -2/3, 0.],
    [0, 0, 1.]]
)
initial_matrix_1 = operation * initial_matrix_1

print('Matrix #1 after Operation :')
display(initial_matrix_1)

# ===============
operation = np.matrix(
    [[1, -1/2, 0.],
    [0, 1, 0.],
    [0, 0, 1.]]
)
initial_matrix_1 = operation * initial_matrix_1

print('Matrix #1 after Operation :')
display(initial_matrix_1)

# ===============
operation = np.matrix(
    [[1, 0, 0.],
    [0, 1, 0.],
    [0, -1/2, 1.]]
)
initial_matrix_1 = operation * initial_matrix_1

print('Matrix #1 after Operation :')
display(initial_matrix_1)
print('Reached Row Reduced Form :')
print("""
Using the given values derived from the matrix form in reduced row echelor form above,
we get a=2, b=-1, c=0.
""")
print("""
Since there exists a linear combination of all three vectors in w for vector v,
Therefore, vector v must be part of their span.
""")

initial_matrix_1_orig = np.matrix(
    [[2., 1., 3,3],
    [1., -1., 0,3],
    [1., 1., 2,1]]
)
a = 2
b = -1
c = 0


print("""
We can verify this by computing a*v_1 + b*v_2 + c*v_3
""")
print('Result is :{}'.format(
    initial_matrix_1_orig[:,0] * a + initial_matrix_1_orig[:,1] * b + initial_matrix_1_orig[:,2] * c
))

print('Answer to Problem 2.b')
print('Row Operations for Second Initial Matrix')
initial_matrix_2 = np.matrix(
    [[1, -2, -1,0],
    [2, 1, 1,0],
    [3, 2, -1,0]]
)
print('Initial Matrix #2:')
display(initial_matrix_2)

operation = np.matrix(
    [[1, 0, 0.],
    [-2, 1, 0.],
    [0, 0, 1.]]
)
initial_matrix_2 = operation * initial_matrix_2

print('Matrix #2 after Operation :')
display(initial_matrix_2)

operation = np.matrix(
    [[1, 0, 0.],
    [0, 1, 0.],
    [-3, 0, 1.]]
)
initial_matrix_2 = operation * initial_matrix_2

print('Matrix #2 after Operation :')
display(initial_matrix_2)

####
operation = np.matrix(
    [[1, 0, 0.],
    [0, 1/5, 0.],
    [0, 0, 1.]]
)
initial_matrix_2 = operation * initial_matrix_2

print('Matrix #2 after Operation :')
display(initial_matrix_2)

####
operation = np.matrix(
    [[1, 2, 0.],
    [0, 1, 0.],
    [0, 0, 1.]]
)
initial_matrix_2 = operation * initial_matrix_2

print('Matrix #2 after Operation :')
display(initial_matrix_2)

####
operation = np.matrix(
    [[1, 0, 0.],
    [0, 1, 0.],
    [0, -8, 1.]]
)
initial_matrix_2 = operation * initial_matrix_2

print('Matrix #2 after Operation :')
display(initial_matrix_2)

####
operation = np.matrix(
    [[1, 0, 0.],
    [0, 1, 0.],
    [0, 0, -5/14.]]
)
initial_matrix_2 = operation * initial_matrix_2

print('Matrix #2 after Operation :')
display(initial_matrix_2)

####
operation = np.matrix(
    [[1, 0, -.2],
    [0, 1, 0.],
    [0, 0, 1.]]
)
initial_matrix_2 = operation * initial_matrix_2

print('Matrix #2 after Operation :')
display(initial_matrix_2)

####
operation = np.matrix(
    [[1, 0, 0],
    [0, 1, -3/5],
    [0, 0, 1.]]
)
initial_matrix_2 = operation * initial_matrix_2

print('Matrix #2 after Operation :')
display(initial_matrix_2)
print('Note: C^13 and C^23 is supposed to be zero, but I think numpy is trying to get a smaller approximation to zero instead.')
print('Since the matrix can be row reduced and results in no solutions, this means all three vectors can only be linearly independent.')
print('And since all three of them are linearly independent, this means they span all of the 3D space (R^3)')

Answer to Problem 2.a
Row Operations for First Initial Matrix
Initial Matrix #1:


matrix([[ 2.,  1.,  3.,  3.],
        [ 1., -1.,  0.,  3.],
        [ 1.,  1.,  2.,  1.]])

Matrix #1 after Operation :


matrix([[ 1. ,  0.5,  1.5,  1.5],
        [ 1. , -1. ,  0. ,  3. ],
        [ 1. ,  1. ,  2. ,  1. ]])

Matrix #1 after Operation :


matrix([[ 1. ,  0.5,  1.5,  1.5],
        [ 0. , -1.5, -1.5,  1.5],
        [ 1. ,  1. ,  2. ,  1. ]])

Matrix #1 after Operation :


matrix([[ 1. ,  0.5,  1.5,  1.5],
        [ 0. , -1.5, -1.5,  1.5],
        [ 0. ,  0.5,  0.5, -0.5]])

Matrix #1 after Operation :


matrix([[ 1. ,  0.5,  1.5,  1.5],
        [ 0. ,  1. ,  1. , -1. ],
        [ 0. ,  0.5,  0.5, -0.5]])

Matrix #1 after Operation :


matrix([[ 1. ,  0. ,  1. ,  2. ],
        [ 0. ,  1. ,  1. , -1. ],
        [ 0. ,  0.5,  0.5, -0.5]])

Matrix #1 after Operation :


matrix([[ 1.,  0.,  1.,  2.],
        [ 0.,  1.,  1., -1.],
        [ 0.,  0.,  0.,  0.]])

Reached Row Reduced Form :

Using the given values derived from the matrix form in reduced row echelor form above,
we get a=2, b=-1, c=0.


Since there exists a linear combination of all three vectors in w for vector v,
Therefore, vector v must be part of their span.


We can verify this by computing a*v_1 + b*v_2 + c*v_3

Result is :[[3.]
 [3.]
 [1.]]
Answer to Problem 2.b
Row Operations for Second Initial Matrix
Initial Matrix #2:


matrix([[ 1, -2, -1,  0],
        [ 2,  1,  1,  0],
        [ 3,  2, -1,  0]])

Matrix #2 after Operation :


matrix([[ 1., -2., -1.,  0.],
        [ 0.,  5.,  3.,  0.],
        [ 3.,  2., -1.,  0.]])

Matrix #2 after Operation :


matrix([[ 1., -2., -1.,  0.],
        [ 0.,  5.,  3.,  0.],
        [ 0.,  8.,  2.,  0.]])

Matrix #2 after Operation :


matrix([[ 1. , -2. , -1. ,  0. ],
        [ 0. ,  1. ,  0.6,  0. ],
        [ 0. ,  8. ,  2. ,  0. ]])

Matrix #2 after Operation :


matrix([[1. , 0. , 0.2, 0. ],
        [0. , 1. , 0.6, 0. ],
        [0. , 8. , 2. , 0. ]])

Matrix #2 after Operation :


matrix([[ 1. ,  0. ,  0.2,  0. ],
        [ 0. ,  1. ,  0.6,  0. ],
        [ 0. ,  0. , -2.8,  0. ]])

Matrix #2 after Operation :


matrix([[1. , 0. , 0.2, 0. ],
        [0. , 1. , 0.6, 0. ],
        [0. , 0. , 1. , 0. ]])

Matrix #2 after Operation :


matrix([[1.00000000e+00, 0.00000000e+00, 1.22124533e-16, 0.00000000e+00],
        [0.00000000e+00, 1.00000000e+00, 6.00000000e-01, 0.00000000e+00],
        [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 0.00000000e+00]])

Matrix #2 after Operation :


matrix([[ 1.00000000e+00,  0.00000000e+00,  1.22124533e-16,
          0.00000000e+00],
        [ 0.00000000e+00,  1.00000000e+00, -2.22044605e-17,
          0.00000000e+00],
        [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00,
          0.00000000e+00]])

Note: C^13 and C^23 is supposed to be zero, but I think numpy is trying to get a smaller approximation to zero instead.
Since the matrix can be row reduced and results in no solutions, this means all three vectors can only be linearly independent.
And since all three of them are linearly independent, this means they span all of the 3D space (R^3)


## Problem (bonus): Prove Proposition I

<details>
<summary>Hint</summary>
The theorem you need is in Challenge 5A.
</details>

## Definition: (basis)

A set $\{\vec{v_i}\}$ of vectors in $V$ is called a **basis** of $V$ if _any_ of the following conditions hold:

1. The set is a maximally linearly independent set: it is linearly independent, and if you add one more vector, it will no longer be.
2. The set is a minimally spanning set: it spans $V$, and if you drop one vector, it will no longer span $V$.
3. The set is a linearly independent set spanning $V$.

---

Choosing a basis for a vector space is in some sense, choosing its _axes_. Each basis vector represents an axis and its magnitude determines the axis' unit of length.

Also, it can be shown that all bases for a vector space $V$ will have the same number of elements, which we call the **dimension** of $V$ or $\text{dim }V$.

## Example: Standard basis

We now understand why $\{\vec{e_i}\}_{i=1}^n$ are called _basis_ vectors: because they form a basis of $\mathbb{R}^n$.

To see this, verify that they span $\mathbb{R}^n$ and are linearly independent. So by Proposition I, they must serve as a basis (aka the **standard basis**) for $\mathbb{R}^n$.

**Q**: Is $\vec{e} = \begin{bmatrix} 1 \\ 0 \\ 0 \end{bmatrix}$ part of $\mathbb{R}^2$?

<details>
<summary>Answer</summary>
No, because it has three entries.
</details>

---

Point is, there's a different standard basis for every $k$ in $\mathbb{R}^k$.

## Problem 3: Find a basis for $\mathbb{R}^2$ that isn't the standard basis.

Either (1,1) or (-1,1), or (2,3) works

Show solution here through checking any of those vectors if its linearly independent and spans all of V

## Definition: (orthonormal basis)

A set of vectors $\{\vec{v_i}\}$ is **orthonormal** if each vector is orthogonal to every other one in the set, and if all of them are of length 1. That is:

$$
\vec{v_i} \cdot \vec{v_j} = 0
$$

when $i \neq j$, and $|\vec{v_k}| = 1$ for all $\vec{v_k}$.

These vectors then are said to form an **orthonormal basis** for $\text{Span } \{\vec{v_i}\}$.


## Example: The standard basis is orthonormal

We know that $\{\vec{e_i}_{i=1}^n\}$ is a basis for $\mathbb{R}^n$, and they are clearly of length 1. To show then that it is an orthonormal basis for $\mathbb{R}^n$, it is enough to verify that they are all orthogonal to each other.  

## Definition: (orthogonal matrix)

An $n \times n$ matrix $A$ is **orthogonal** if it satisfies any of the following conditions:

1. $A A^T = A^T A = I$, or in other words its transpose is its inverse: $A^T = A^{-1}$.
2. The columns of $A$ form an orthonormal basis of $\mathbb{R}^n$.
3. For any $\vec{v}, \vec{w} \in \mathbb{R}^n$,

$$
A\vec{v} \cdot A\vec{w} = \vec{v} \cdot \vec{w}
$$

## Definition: (kernel and image)

Let $T: \mathbb{R}^n \to \mathbb{R}^m$ be a linear transformation.

1. The **kernel** of $T$ or $\text{ker } T$ is the set of vectors $\vec{x} \in \mathbb{R}^n$ such that $T(\vec{x}) = \vec{0}$.
2. The **image** of $T$ or $\text{img } T$ is the set of vectors $\vec{w} \in \mathbb{R}^m$ such that there exists a vector $\vec{v} \in \mathbb{R}^n$ with $T(\vec{v}) = \vec{w}$

---

In other words, the _kernel_ tells you all the vectors a linear transformation sends to $\vec{0}$, while the _image_ is the set of vectors the transformation can possibly output.


## Example: Vector in a kernel

Let $A = \begin{bmatrix} 1 & 1 & 1 \\ 2 & -1 & 1 \end{bmatrix}$ be (the matrix that represents) a linear transformation. Then $\vec{v} = \begin{bmatrix} -2 \\ -1 \\ 3 \end{bmatrix}$ is in $\text{ker } A$, because:

$$
\begin{bmatrix} 1 & 1 & 1 \\ 2 & -1 & 1 \end{bmatrix}
\begin{bmatrix} -2 \\ -1 \\ 3 \end{bmatrix}
=
\begin{bmatrix} 0 \\ 0 \end{bmatrix}
$$

---

If $T: \mathbb{R}^n \to \mathbb{R}^m$ is a linear transformation, then $\text{ker }T$ is a vector subspace of $\mathbb{R}^n$ and $\text{img }T$ is a vector subspace of $\mathbb{R}^m$.

## Proposition II: Kernel, image, and solutions to systems of equations

Let $T: \mathbb{R}^n \to \mathbb{R}^m$ be a linear transformation. Then the system of (linear) equations $T(\vec{x}) = \vec{b}$ has:

1. at _most_ one solution for every $\vec{b} \in \mathbb{R}^n$ if and only if $\text{ker }T = \{\vec{0}\}$

2. at _least_ one solution for every $\vec{b} \in \mathbb{R}^n$ if and only if $\text{img }T = \mathbb{R}^m$

## Problem (bonus): Prove Proposition II.

## Proposition III: Dimension and rank

Let $T: \mathbb{R}^n \to \mathbb{R}^m$ be a linear transformation. Then:

$$
\text{dim }(\text{ker }T) + \text{dim }(\text{img }T) = n
$$

(the dimension of $\mathbb{R}^n$)

Furthermore, $\text{dim }(\text{img }T)$ is called the **rank** of T.

---

It can be shown by a somewhat involved proof that, if $\tilde{T}$ is the row-reduced form of the matrix $[T]$ representing $T$, then $\text{dim }(\text{img }T)$ is equal to the number of pivotal columns, while $\text{dim }(\text{ker }T)$ is equal to the non-pivotal columns.

## Example: Fibonacci sequence

The Fibonacci numbers $1, 1, 2, 3, 5, 8, 13, \dots$ are usually defined by the following procedure: take the last two numbers and then add them together to get the next one. In equation form:

$$
\begin{cases}
a_0 = a_1 &= 1 \\
a_{n+1} &= a_n + a_{n-1}
\end{cases}
$$

or in matrix form:

$$
\begin{bmatrix}
a_n \\
a_{n+1}
\end{bmatrix} =
\begin{bmatrix}
0 & 1 \\
1 & 1
\end{bmatrix}
\begin{bmatrix}
a_{n-1} \\
a_{n}
\end{bmatrix}
$$

Is there a better way of generating the sequence? If we try to do the matrix multiplication repeatedly, we'll find that:

$$
\begin{bmatrix}
a_n \\
a_{n+1}
\end{bmatrix} =
\begin{bmatrix}
0 & 1 \\
1 & 1
\end{bmatrix}^n
\begin{bmatrix}
1 \\
1
\end{bmatrix}
$$

which looks beautiful but then if you actually try to multiply this out, you realise you're still performing the same calculations. Are we out of luck?

Of course not. Let:

$$
P =
\begin{bmatrix}
2 & 2 \\
1 + \sqrt{5} & 1 - \sqrt{5}
\end{bmatrix}
$$

which means

$$
P^{-1} = \frac{1}{4\sqrt{5}}
\begin{bmatrix}
\sqrt{5} - 1 & 2 \\
\sqrt{5} + 1 & -2
\end{bmatrix}
$$

Now, if $A = \begin{bmatrix} 0 & 1 \\ 1 & 1 \end{bmatrix}$, then we can write:

$$
P^{-1} A P =
\begin{bmatrix}
\frac{1 + \sqrt{5}}{2} & 0 \\
0 & \frac{1 - \sqrt{5}}{2}
\end{bmatrix}
$$

This is a _diagonal_ matrix! And we know from a previous session that powers of diagonal matrices just square the entries in the diagonal. Hence:

$$
(P^{-1} A P)^n = (P^{-1} A P)(P^{-1} A P)\dots(P^{-1} A P)
= (P^{-1} A^n P)
$$

since all the $P P^{-1} = P^{-1} P = I$.

Solving for $A^n$ then by multiplying $P$'s and $P^{-1}$'s, we get:

$$
A^n = P \, (P^{-1} A P)^n \, P^{-1}
$$

And expanding this out by substituting the values (and letting $\lambda_1 = \tfrac{1+\sqrt{5}}{2}$, $\lambda_2 = \tfrac{1-\sqrt{5}}{2}$), we obtain:

$$
A^n = \frac{1}{2\sqrt{5}}
\begin{bmatrix}
\lambda_1^n (\sqrt{5} - 1) + \lambda_2^n (\sqrt{5} + 1) &
2\lambda_1^n - 2\lambda_2^n \\
\lambda_1^{n+1} (\sqrt{5} - 1) + \lambda_2^{n+1} (\sqrt{5} + 1) &
2\lambda_1^{n+1} - 2\lambda_2^{n+1} \\
\end{bmatrix} =
\begin{bmatrix}
0 & 1 \\
1 & 1
\end{bmatrix}^n
$$

And so by our original matrix equation (the one with $A^n$), we can obtain a _direct_ formula for the nth Fibonacci number $a_n$:

$$
a_n = \left( \frac{5 + \sqrt{5}}{10} \lambda_1^n \right) + \left( \frac{5 - \sqrt{5}}{10} \lambda_2^n \right)
$$

Isn't this remarkable? We only need to calculate $\lambda_1$ and $\lambda_2$ now to get to _any_ Fibonacci number, no need to bother unrolling the recurrence.

## Definition: (eigenvector, eigenvalue, multiplicity)

Let $V$ be a vector space and $T: V \to V$ be a linear transformation (here, we blur the notation between $T$ the transformation and its corresponding matrix $T$).

Then a _nonzero_ vector $\vec{v}$ such that:

$$
T{\vec{v}} = \lambda \vec{v}
$$

for some scalar $\lambda$ is called an **eigenvector** of $T$, and $\lambda$ is its corresponding **eigenvalue**. The dimension of the set $\{\vec{v} | T{\vec{v}} = \lambda \vec{v}\}$, called the **eigenspace**, is called the **multiplicity** of $\lambda$.

---

In other words, we are now talking about the matrix equation $A\vec{x} = \lambda \vec{x}$.

What this set up tells us is that we are interested in finding the vectors for which applying $T$ results in at most a scaling of said vectors. In some sense, these _eigenvectors_ represent those vectors that are merely stretched, never rotated or sheared. They are directions preserved by $T$, and so knowing what they are goes a long way towards characterising what $T$ really does.

Also note that $\lambda$ may be a complex number.



![img](https://i.postimg.cc/dQxjTGjx/shear.png)

_Fig. 1: In this image (from [TreyGreer62](https://en.wikipedia.org/wiki/Eigenvalues_and_eigenvectors#/media/File:Mona_Lisa_eigenvector_grid.png) of Wikipedia), the red arrow is sheared by the transformation but the blue arrow stays in the same direction. Therefore, it is an eigenvector._


## Problem 4: Eigenproblems

a. Explain why only square matrices can have eigenvectors.

b. Show that if $T{\vec{v}} = \lambda \vec{v}$, then $T^k{\vec{v}} = \lambda^k \vec{v}$.

### Answer to Problem 4.a
- In a computational perspective, you can't really compute eigenvectors and eigenvalues without the determinant, so only square matrices who have a determinant (unlike non square matrices) can have eigenvectors.
- And in an intuition and geometric perspective, only square matrices represents transformations within the same dimensional space in which the concept of eigenvectors can exist, but in non square matrices they represent transformations that change the dimensionality of space, making it impossible for vectors to retain their direction after the transformation, thus invalidating the concept of eigenvectors.
### Answer to Problem 4.b
We can prove this is true using mathematical induction.

For the base case:
- $T{\vec{v}} = \lambda \vec{v}$ (k=1):
This is the given condition/assumption already, so the base case holds.

Inductive Hypothesis:
- Assume that $T^k\vec{v} = \lambda^k \vec{v}$ for some positive integer $k$.

Inductive Step:
- For the next steps, we want to prove that $T^{k+1}\vec{v} = \lambda^{k+1} \vec{v}$. We can do this by using existing linear transformation properties and inference.
- Steps:
 - $T^{k+1}\vec{v} = T(T^{k} \vec{v})$
 - $T^{k+1}\vec{v} = T(\lambda^{k} \vec{v})$
   - as per our inductive hypothesis
 - $T^{k+1}\vec{v} = \lambda^{k}(T\vec{v})$
   - Since $T$ is a linear transformation, it follows the distributive property:
 - $T^{k+1}\vec{v} = \lambda^{k}(\lambda\vec{v})$
   - As per the base case
 - $T^{k+1}\vec{v} = \lambda^{k+1} \vec{v}$
   - Simplifying the terms in the right side

Therefore, we have shown that if the statement holds for k, it also holds for k + 1.

As per principle of mathematical induction, the statement holds for all positive integers k. Or in other words, if $T{\vec{v}} = \lambda \vec{v}$, then $T^k{\vec{v}} = \lambda^k \vec{v}$.


## Definition: (eigenbasis)

A basis for a vector space $V$ is an **eigenbasis** of $V$ for a linear transformation $T$ if each element of the basis is an eigenvector of $T$.

## Problem 5: Demystifying the Fibonacci formula

a. Verify that the columns of $P$ in the example above form an eigenbasis of $\mathbb{R}^2$ for the linear transformation represented by $A = \begin{bmatrix} 0 & 1 \\ 1 & 1 \end{bmatrix}$

b. Verify that the diagonals $\lambda_1$ and $\lambda_2$ of $P^{-1} A P$ are the corresponding eigenvalues of the eigenvectors above.

c. Plot the first eigenvector $\begin{bmatrix} 2 \\ 1 + \sqrt{5} \end{bmatrix}$ of $P$ and the first 10 Fibonacci vectors $\begin{bmatrix} a_n \\ a_{n+1} \end{bmatrix}$. How are they related?

In [ ]:
import numpy as np

matrix([[ 0.61803399, -1.61803399],
        [ 1.        ,  1.        ]])

In [ ]:
import numpy as np
import math
# P_val = 1 + math.sqrt(5)
sqr_5 = math.sqrt(5)

P_2 = np.matrix([
    [.5*(-1+sqr_5),.5*(-1-sqr_5)],
     [1,1]]
)
P_2

A = np.matrix([[0,1], [1,1]])
P = np.matrix([[2, 2], [1+sqr_5,1 - sqr_5 ]])

eigenvalues = np.matrix([(1 +sqr_5)/2 ,(1 -sqr_5)/2])

P_2 = np.matrix([
    [.5*(-1+sqr_5),.5*(-1-sqr_5)],
     [1,1]]
)

In [ ]:
# Solution for Problem 5.a
# To check if P is an eigenbasis, we check the following:
# - first if its an eigenvector in the first place and then
# - check if its linearly independent.

# Check first if its an eigenvector
# we can do this by checking if both columns equals to A(x) = z(x), where z is the given eigenvalues.
a = A * P[:,0]
b =  eigenvalues[0,0] * P[:,0]
print(f'{a.T} == {b.T} ') # Note: I just transposed to make it slightly easier to read/visualize.

a_a = A * P[:,1]
b_b = eigenvalues[0,1] * P[:,1]
print(f'{a_a.T} == {b_b.T} ') # Note: I just transposed to make it slightly easier to read/visualize.

# Next, check if these two vectors are linearly independent, you can check these either by
# - checking its determinant is non zero or creating an augmented matrix and solving the combination of both for the zero vector.
# - Add the zero vector and compute towards the zero vector
P_determinant = np.linalg.det(P)
print(f'Solution #1: Determinant is {P_determinant}, since its not 0, both vectors are linearly independent\n which proves it spans all of R^2, thus making it a valid basis vector.')
print('Solution #2:As suggested, you can also find this by computing both vectors in an augmented matrix towards the zero vector')
print('Demonstrated as follows:')
P_sample = np.matrix([[2, 2,0], [1+sqr_5,1 - sqr_5,0 ]])

operation_1 = np.matrix(
    [[1/2, 0],
    [0., 1]],
)
P_sample = operation_1 * P_sample
print('Matrix #1 after Operation 1:')
display(P_sample)

operation_2 = np.matrix(
    [[1, 0],
    [ -P_sample[1,0], 1]], # get the value to minus from existing matrix, you apparently need to do this due to precision
)
P_sample = operation_2 * P_sample
print('Matrix #1 after Operation 2:')
display(P_sample)

operation_3 = np.matrix(
    [[1, 0],
    [ 0, (1 / P_sample[1,1])]], # multiply by its reciprocal,
    # get the value to minus from existing matrix, you apparently need to do this due to precision
)
P_sample = operation_3 * P_sample
print('Matrix #1 after Operation 3:')
display(P_sample)
operation_4 = np.matrix(
    [[1, -1],
    [ 0, 1]], # multiply by its reciprocal,
    # get the value to minus from existing matrix, you apparently need to do this due to precision
)
P_sample = operation_4 * P_sample
print('Matrix #1 after Operation 4:')
display(P_sample)

[[3.23606798 5.23606798]] == [[3.23606798 5.23606798]] 
[[-1.23606798  0.76393202]] == [[-1.23606798  0.76393202]] 
Solution #1: Determinant is -8.944271909999157, since its not 0, both vectors are linearly independent
 which proves it spans all of R^2, thus making it a valid basis vector.
Solution #2:As suggested, you can also find this by computing both vectors in an augmented matrix towards the zero vector
Demonstrated as follows:
Matrix #1 after Operation 1:


matrix([[ 1.        ,  1.        ,  0.        ],
        [ 3.23606798, -1.23606798,  0.        ]])

Matrix #1 after Operation 2:


matrix([[ 1.        ,  1.        ,  0.        ],
        [ 0.        , -4.47213595,  0.        ]])

Matrix #1 after Operation 3:


matrix([[1., 1., 0.],
        [0., 1., 0.]])

Matrix #1 after Operation 4:


matrix([[1., 0., 0.],
        [0., 1., 0.]])

### Answer to Problem 5.b
Although we can just plug the existing values of $\lambda_1$ and $\lambda_2$ and use the following equation, $A\vec{x} = \lambda \vec{x}$ to prove this is true,

a more thorough and believable way to verify that $\lambda_1$ and $\lambda_2$ are the eigenvectors for the ones above, we can actually just derive it as we would normally would!

So to get the eigenvalues of a transformation, we use the following formula:
$det(A - (\lambda)I)=0$

Using this formula we get:
- $det(A - (\lambda)I) = 0$
- $det(\begin{bmatrix} 0 - λ & 1 \\ 1 & 1-λ\end{bmatrix}) = 0$
- $ λ^2 - λ -1  = 0$
- Deriving the solutions for this quadratic results in the following, which is the same as the one given above!
 - $λ^1 = \frac{1+\sqrt{5}}{2}$
 - $λ^2 = \frac{1-\sqrt{5}}{2}$



In [ ]:
a = P[:,0] * eigenvalues[0,0]

In [ ]:
a = a[:,0] * eigenvalues[0,0]
a

matrix([[22.18033989],
        [35.88854382]])

In [ ]:
# Answer to Problem 5.c
import plotly.express as px
import plotly.graph_objects as go

test_x = []
test_y = []
for i in range(2,20):
  val = P[:,0] * i
  test_x.append(val[0,0])
  test_y.append(val[1,0])

# new_val = P[:,0] * eigenvalues[0,0]
# test_x.append(new_val[0,0])
# test_y.append(new_val[1,0])
# for i in range(3,9):
#   new_val = new_val * eigenvalues[0,0]
#   test_x.append(new_val[0,0])
#   test_y.append(new_val[1,0])


x_P = [P[0,0]]
y_P = [P[1,0]]
x_fibonacci_vectors = [1,1,2,3,5,8,13,21,34,55]
y_fibonacci_vectors = [1,2,3,5,8,13,21,34,55,89]
layout = go.Layout(
    title = "Demistified Eigenvector",
    yaxis = {"title": "y"},
    xaxis = {"title": "x"},
    margin = dict(l=40,r=40,t=60,b=40)
)
fig = go.Figure(layout = layout)
eigenvector_trace = go.Scatter(
            x = x_P,
            y = y_P,
            mode = "markers",
            name = "Eigenvector",
        )
fig.add_traces(eigenvector_trace)
scaled_eigenvector_trace = go.Scatter(
            x = test_x,
            y = test_y,
            mode = "markers",
            name = "Scaled Eigenvector",
        )
fig.add_traces(scaled_eigenvector_trace)
fibonnaci_trace = go.Scatter(
            x = x_fibonacci_vectors,
            y = y_fibonacci_vectors,
            mode = "markers",
            name = f"Fibonacci Numbers",
        )
fig.add_traces(fibonnaci_trace)
print("""Plotting both vectors let us to see that these two vectors are closely related,
or in other words, their range of possible higher values are very close and they point at exactly the same direction.
To better visualize this, I made two graphs using the possible values of both vectors for higher values.
In the first graph, we can see very clearly that some of the eigenvector's values  are very close,
hinting that we can derive possible fibonnaci numbers in the same line.
And finally in the second graph,
it just shows very clearly that they are almost in the same line with only very little difference in direction.
In conclusion, plotting the eigenvector against the expected fibonacci numbers, shows us clearly that because they are similar vectors,
we can derive possible values interchangeably from one vector to another.
""")
fig.show()
fig = go.Figure(layout = layout)
eigenvector_trace = go.Scatter(
            x = x_P,
            y = y_P,
            mode = "markers",
            name = "Eigenvector",
        )
fig.add_traces(eigenvector_trace)
scaled_eigenvector_trace = go.Scatter(
            x = test_x,
            y = test_y,
            mode = "markers",
            name = "Scaled Eigenvector",
        )
fig.add_traces(scaled_eigenvector_trace)
fibonnaci_trace = go.Scatter(
            x = x_fibonacci_vectors,
            y = y_fibonacci_vectors,
            mode = "lines",
            name = f"Fibonacci Numbers",
        )
fig.add_traces(fibonnaci_trace)
fig.show()

Plotting both vectors let us to see that these two vectors are closely related,
or in other words, their range of possible higher values are very close and they point at exactly the same direction.
To better visualize this, I made two graphs using the possible values of both vectors for higher values.
In the first graph, we can see very clearly that some of the eigenvector's values  are very close,
hinting that we can derive possible fibonnaci numbers in the same line.
And finally in the second graph, 
it just shows very clearly that they are almost in the same line with only very little difference in direction.
In conclusion, plotting the eigenvector against the expected fibonacci numbers, shows us clearly that because they are similar vectors,
we can derive possible values interchangeably from one vector to another.



## Definition: (diagonalizable matrix)

A matrix $A$ is **diagonalisable** if there exists a matrix $P$ such that $P^{-1} A P$ is diagonal.

## Proposition IV: Diagonalization

Let $A$ be an $n \times n$ matrix and $P = [\vec{v_1}, \dots, \vec{v_n}]$ an invertible $n \times n$ matrix.

Then the following are true:

1. The eigenvalues of $A$ and the eigenvalues of $P^{-1} A P$ coincide.
2. If $P^{-1} A P$ is a diagonal matrix with diagonal entries $\lambda_i$, the columns of P are eigenvectors of $A$, with eigenvalues $\lambda_i$

## Problem (bonus): Prove Proposition IV.

## Proposition V: Eigenvectors with distinct eigenvalues are linearly

---

independent

If $A: V \to V$ is a linear transformation and $\{\vec{v_i}\}$ are eigenvectors of $A$ with distinct eigenvalues $\{\lambda_i\}$, then $\{\vec{v_i}\}$ are linearly independent.

---

In particular, there are at most $\text{dim }V = n$ eigenvalues.

## Problem 6: Prove Proposition V by contradiction.

Hint: you will need to use $\lambda_j I - A$, where $0 \leq j \leq i$.

### My Proof:
the way to prove Proposition V is true by contradiction is going with the assumption that the opposite is true, which is all eigenvectors are linearly dependent and find a contradiction. I do this through the steps below:
- Suppose that $\{\vec{v_i}\}$ were linearly dependent.
- if it is there should be a eigenvector in  $\{\vec{v_i}\}$ where it results in the linear combination of all the vectors preceding it:
 - $\vec{v}_{j+1} = c_1v_1 + c_2v_2 ... + c_jv_j $ (equation #1)
- Since $\vec{v}_{j+1}$ is an eigenvector and all of what is being summed to it is an eigenvector, all vectors in $\{\vec{v_i}\}$ can be both represented as $\lambda v$, therefore:
 - $\lambda_{j+1}\vec{v}_{j+1} = (\lambda_{1})c_1v_1 + (\lambda_{2})c_2v_2 ... + (\lambda_{j})c_jv_j $ (equation #2)
- now, if we were to multiply equation #1 with $\lambda_{j+1}$ we eventually get:
 - $(\lambda_{j+1})\vec{v}_{j+1} = (\lambda_{j+1})c_1v_1 + (\lambda_{j+1})c_2v_2 ... + (\lambda_{j+1})c_jv_j $ (equation #1)
- we can then get the difference of equation #2 and #1 since they are equa and group like terms to get the following:
 -  $0 =  c_1(\lambda_1 -\lambda_{j+1})v_1 + c_2(\lambda_2 -\lambda_{j+1})v_2 + ... + c_j(\lambda_j -\lambda_{j+1})v_j$

Reading upon the new equation derived from the difference of two equations, we  infer a few things:
-  $(\lambda_j -\lambda_{j+1})$ - each combination pair in this equation will only result in a non-zero value since both $\lambda_j$ and $\lambda_{j+1}$ are distinct.
- all vectors of $v_j$ in this equation can only be non-zero due to the definition of eigenvectors.

Infering from these two information derived, then in this equation  $c_j$ must be zero for this equation to work.

And thus, **this implies that the assumption $\vec{v}_{j+1}$ can be a linear combination of some vectors, or in other words $\vec{v}_{j+1} c_1v_1 + c_2v_2 ... + c_jv_j $ is not true at all. Therefore, all vectors in  $\{\vec{v_i}\}$ must have been linearly independent after all.**





---

So what have we done? We've seen that to study a linear transformation, it is enough to look at its eigenbasis, and furthermore, that there is a process called _diagonalisation_ that simplifies certain calculations involving a transformation without changing what it is doing.

This was particularly salient in the Fibonacci problem when we constructed $P$ from the eigenvectors of $A = \begin{bmatrix} 0 & 1 \\ 1 & 1 \end{bmatrix}$ and arrived at a closed-form formula for $a_n$ after forming $P^{-1} A P$.

To understand what an eigenbasis meant, it was necessary for us to understand how and when we can combine vectors and what kind of mathematical objects we can build from them.

But how do we find the eigenbasis for a linear transformation in the first place? And how does that help us understand neural networks? Stay tuned for more. 🙂

## Additional resources

* _The Essence of Linear Algebra_, by 3Blue1Brown: [LINK](https://www.3blue1brown.com/topics/linear-algebra) (2-3 hours)
* _Orthogonal Vectors and Subspaces_, an MIT OpenCourseWare lecture video by G. Strang: [LINK](https://openlearninglibrary.mit.edu/courses/course-v2:OCW+18.06SC+2T2019/courseware/201102cc58fd4300b62bdba016238741/587d3844f821441d94418db8b125357e/?activate_block_id=block-v1%3AOCW%2B18.06SC%2B2T2019%2Btype%40sequential%2Bblock%40587d3844f821441d94418db8b125357e) (~50 mins)
* _Eigenvalues and Eigenvectors_, by G. Strang: [LINK](https://openlearninglibrary.mit.edu/courses/course-v1:OCW+18.06SC+2T2019/courseware/201102cc58fd4300b62bdba016238741/ff5e10d34f074173a7ace8d54d0f5238/?activate_block_id=block-v1%3AOCW%2B18.06SC%2B2T2019%2Btype%40sequential%2Bblock%40ff5e10d34f074173a7ace8d54d0f5238) (~50 mins)
* _Diagonalization and Powers of A_, by G. Strang: [LINK](https://openlearninglibrary.mit.edu/courses/course-v1:OCW+18.06SC+2T2019/courseware/201102cc58fd4300b62bdba016238741/a5d0b53714b646839c528115ef3157b7/?activate_block_id=block-v1%3AOCW%2B18.06SC%2B2T2019%2Btype%40sequential%2Bblock%40a5d0b53714b646839c528115ef3157b7) (~50 mins)